blank_issues_enabled: true # force the usage of a template
contact_links:
  - name: Feature Requests, support and consulting
    url: https://github.com/sponsors/petyosi
    about: If you have troubles integrating React Virtuoso in your project and need dedicated assistance with it, contact me over my the email in my profile.
